### ISSUE TITLE
default fps when capture 

### ISSUE THREAD

**Issue by c1ngular** [vladimirvivien/go4vl#15]
nice job . 
i see the default/base fps is set to 10 from here :
https://github.com/vladimirvivien/go4vl/blob/40b41ba86c5c8d169bae1bcce5ec16605db44e6f/v4l2/device/device.go#L231, is there any way to detect and set a default fps value(rather than 10) supported by opened device ?  
thanks

**Comment by vladimirvivien** [comment]
Thank you @c1ngular great idea.

**Comment by vladimirvivien** [comment]
Default fps was implemented in last release. I think this issue can be closed.
