### ISSUE TITLE
Implement device control

### ISSUE THREAD

**Issue by vladimirvivien** [vladimirvivien/go4vl#19]
Add code to allow device control using v4l2_ext_control/v4l2_ext_controls.

**Comment by ruidscampos** [comment]
Thanks for the great work. Wondering if this is intended to bring support for exposure control, as it would be great to do that when using multiple cameras.

**Comment by vladimirvivien** [comment]
Yes, it's code to support device user-control (at the very least) and eventually extended control!

**Comment by vladimirvivien** [comment]
Added support for user device controls (see #23)

**Comment by ruidscampos** [comment]
That was fast, thanks!!!
