### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by oyarzun** [vladimirvivien/go4vl#22]
While testing the webcam example on a raspberry pi, top shows that the memory continues to grow. 

Is anyone else seeing this behavior?

**Comment by vladimirvivien** [comment]
Thanks for bringing this to my attention. 
Which RPi (3 or 4) ?
Also, how many connections were opened?

**Comment by oyarzun** [comment]
It was on a RPi 3 B+. I initially tried it with just one connection then added another 2, but the memory increases at about the same rate.

**Comment by vladimirvivien** [comment]
@oyarzun I was able to replicate the issue while running the webcam example. I am going to spend sometimes this weekend to investigate. Thanks again for checking the project out and take time to point this out.

**Comment by vladimirvivien** [comment]
@oyarzun please check out the fix.

**Comment by vladimirvivien** [comment]
Update: I ran a camera feed for about 25 consecutive hours, 
* mem consumption remained stable at 1 %
* CPU utilization constant at about 3 %
* Pushing 30 fps HD to browser

**Comment by oyarzun** [comment]
@vladimirvivien I also confirmed that there is no longer a memory leak. Thanks for fixing the leak and the library in general.
