### ISSUE TITLE
Single capture at regular intervals

### ISSUE THREAD

**Issue by ruidscampos** [vladimirvivien/go4vl#33]
What's the best approach to do a single capture at regular intervals.
There is an example for snapshot, but that one closes the device once it finishes storing the image.

In a scenario where we want to regularly capture, sometimes with a couple seconds difference, others with minutes, should the device be closed or kept open?

If open, what is the best approach to ensure getting the latest frame without causing any issues or large memory footprint?

Thanks

**Comment by vladimirvivien** [comment]
Hi @ruidscampos 
Thanks for your interest in the project.  So, based on your question, I think the most important thing is to have a long-running process that intermittently open the device, take a pic, then close the device.

You can do this in Go by creating a program that does the following:
*  Start a loop that runs forever (or until shutdown is signaled) 
* Use a `time.Sleep`, with specified interval value to wait
* Once time has elapsed, then open the device, take picture, close device.
* Then go back at start of loop.

Hope that helps.

**Comment by ruidscampos** [comment]
Thank you @vladimirvivien for your quick reply and suggestion.
As per my previous reply to another issue, really appreciate all the work you've done with this project.

Regarding the open+close, is this heavy on the processing?
My use case has a dynamic cadence, and in some cases the cadence could be 1 frame every two seconds, or even 1fps, for a short period of time, say 20 seconds, and then be different.
So does it make sense to use a straight capture and supply 1fps, or do the open close?

Ran some tests with v0.0.3 when I was doing some initial testing and with the cameras I'm using, if I select an fps or resolution that is not natively supported (as reported by v4l), the usb bus will consume a lot more bandwidth than if I select an fps and resolution that is natively supported.

Thus my questions, trying to understand constraints and best way to use it for my scenario, given you have a lot more knowledge of it than me.

In regards to time.Sleep, I tend to use a for with a ticker within a select case.
This allows me to have a closing channel and not wait for the sleep to finish when I want to terminate thread.
It also ensures a more accurate interval, if my execution is faster than the interval.

Here's a pseudo-example of how I tend to approach it:
> // Start separate thread for regular interval execution
> closeChan := chan bool
> myTicker := time.NewTicker(Duration.Seconds * 2)
> go IntervalExecution()

> // Stop the execution
> myTicker.Stop()
> closeChan <- true

> func IntervalExecution() {
> for {
> // Wait for the first channel to have something
> select {
> case <- closeChan:
> return
> case <- myTicker.C:
> // Do something here
> // Execution here should be faster than ticker duration
> }}}

**Comment by vladimirvivien** [comment]
@ruidscampos Thanks for elaborating your scenario.
There are two cases to consider
* If this is running on a dedicated machine and no other process will open the camera device, then I don't see the harm in keeping the device open
* If, on the other hand, other processes may need the device, then you should close after using.

It sounds like this will be dedicated. So, I think you should be ok with keeping the device open.

Also, the pseudo example looks Ok and should work.  Please let me know how it turns out.

**Comment by ruidscampos** [comment]
@vladimirvivien thanks.
I'll keep it open and see how it behaves, will let you know of any findings.
