### ISSUE TITLE
Golang 1.20 compiler errors

### ISSUE THREAD

**Issue by ruidscampos** [vladimirvivien/go4vl#44]
There appear to be some changes in 1.20 that cause the library to not compile and report some issues on my windows machine.
Reverting to the latest 1.19 makes it work again.

It appears to be related to the use of consts and 1.20 doesn't seem to like it for some reason.
Found some cases with a similar report that implied a constant overflow check, but your code seems correct in that regard.

It reports this with go build ./... on a project:

..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\types.go:11:15: undefined: Capability
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\types.go:12:14: undefined: IOType
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\types.go:23:15: undefined: BufType
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:33:17: undefined: sys.Openat
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:33:28: undefined: sys.AT_FDCWD
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:53:13: undefined: sys.Close
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:57:43: undefined: sys.Errno
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:59:22: undefined: sys.Syscall
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:59:34: undefined: sys.SYS_IOCTL
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:63:12: undefined: sys.EINTR
..\..\..\..\go\pkg\mod\github.com\vladimirvivien\go4vl@v0.0.5\v4l2\syscalls.go:63:12: too many errors

It also complains inside VSCode anywhere the consts are used within a project.
I don't have the v4l2 source files in my windows box, but 1.19 never complained about it.

Unsure how this could be fixed, if at all, and if this is a golang issue that could be to raise with the go team.
Thought I'd raise it and get your opinion on it.

**Comment by vladimirvivien** [comment]
@ruidscampos thank you for brining this to my attention. Will mark it appropriately.

**Comment by vladimirvivien** [comment]
HI @ruidscampos 
You mentioned that you are running on your Windows machine. 
Are you cross compiling? If so, how are you cross compiling your code ?
Or, are you using the Windows Linux Subsystem (WSL) ? If so, how are you compiling in there?

**Comment by ruidscampos** [comment]
Hi @vladimirvivien 
I develop on my windows machine with VSCode and then build via CICD on a linux machine that is identical to the final machine that will run the build.

With 1.19 on windows there are no errors in VSCode and I'm able to build most of it but then fails on CGO with a nice error:
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

With 1.20 on windows there are several errors reported in VSCode wherever I use any of the constants, and when building outputs the error I previously raised also regarding the constants.

I haven't had the time to update the CICD to 1.20 and built it there, but can do it later this week and let you know the result.

**Comment by vladimirvivien** [comment]
Hi @ruidscampos 
Apologies for the delay in replying. 

Yes, you are hitting a change Go version 1.20 (see detail [here](https://tip.golang.org/doc/go1.20#cgo)). Basically, version 1.20 does no longer satisfies the C tool chain for environment that does not already have it. Meaning, you will need to install gcc yourself on your machine.

If you don't want to do that, you can install the Zig compiler (I think it works on Windows Linux subsystem). See detail here for building using Zig [here](https://github.com/vladimirvivien/go4vl/blob/main/examples/README.md#cross-compile-with-zig-toolchain).

I was NOT able to recreate your issue. I was able to build on my machine:

```
go version
go version go1.20.2 darwin/arm64

CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 CC="zig cc -target arm-linux-musleabihf" CXX="zig c++ -target arm-linux-musleabihf" go build -o simple-cam ./simplecam
```

**Comment by ruidscampos** [comment]
Hi @vladimirvivien, thanks for finding the origin, I'll give it another try with your indications.
