### ISSUE TITLE
DMA-BUF support 

### ISSUE THREAD

**Issue by c1ngular** [vladimirvivien/go4vl#58]
I want to preview captured frame as fast/performant as possible , i.e. pass dma buf to gstreamer／drm to display it (zero-copy) , could this lib export such an option (DMA BUF )  in addition to MMAP way?

Thanks

**Comment by vladimirvivien** [comment]
If I understand your request @c1ngular , you want to access the MMAP directly ? Right now it is not exposed, but that's an idea. Please confirm.
