### ISSUE TITLE
Unable to set any frame size other than the default 640x480

### ISSUE THREAD

**Issue by McHauge** [vladimirvivien/go4vl#8]
Hi, I seem to have a problem setting the image size correctly and it keeps defaulting to the default 640x480, even when using your webcam.go example and changing the with and height to 1280x720 still resolves in a 640x480 picture. the capture card is able to provide an MJPEG of 720p as well as 1080p and this also works via this pkg: https://github.com/blackjack/webcam 
but I cant get the same to work here, even though I like the rest of the implementation here a bit better.

Would you mind giving an example of a working webcam.go or capture.go with a different image size just as a reference to look at.

**Comment by vladimirvivien** [comment]
I have seen that issue. I may have a fix coming soon (or at least a workaround).

**Comment by vladimirvivien** [comment]
Thanks again for the kind words.

**Comment by vladimirvivien** [comment]
@McHauge I am working on a refactor that uses cgo-generated Go types (instead of hand crafted).  Please give it a try to see if your problem goes away 

https://github.com/vladimirvivien/go4vl/tree/cgo-refactor

**Comment by vladimirvivien** [comment]
Setting format sizes were addressed in previous releases. So this issue can be closed.
